### ISSUE TITLE
Unknown file format in russian Apple Music links

### ISSUE THREAD

**Issue by MrVaDiM4iK** [topi314/LavaSrc#103]
Lavalink version: 3.7.8
Plugin version: 3.2.6

This error occurs when I insert a link to a Russian playlist, track or album
Link: https://music.apple.com/ru/album/оставаться-счастливо/1696629818?i=1696629819
![image](https://github.com/topi314/LavaSrc/assets/48054172/773df26d-daa1-4e68-8a5c-05f3e921a81b)

Error stack:
```java
2023-08-14 09:32:07.515  INFO 30 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://music.apple.com/ru/album/оставаться-счастливо/1696629818?i=1696629819"
2023-08-14 09:32:08.494 ERROR 30 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Load failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Unknown file format.
        at com.sedmelluq.discord.lavaplayer.source.ProbingAudioSourceManager.handleLoadResult(ProbingAudioSourceManager.java:34) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioSourceManager.loadItem(HttpAudioSourceManager.java:81) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:428) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:410) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:208) ~[lavaplayer-1.5.0.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1623) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.5.0
  os.arch: amd64
  os.name: Linux
  os.version: 5.15.0-73-generic
  java.vendor: Azul Systems, Inc.
  java.version: 20.0.2
  java.runtime.version: 20.0.2+9
  java.vm.version: 20.0.2+9```

**Comment by topi314** [comment]
fix: include non lain characters in https://github.com/topi314/LavaSrc/blob/af85cb6ed75de07ee3345e48792aa8d6459318dc/main/src/main/java/com/github/topisenpai/lavasrc/applemusic/AppleMusicSourceManager.java#L34

**Comment by muralianand12345** [comment]
I face the same issue when I try to play a Spotify playlist or music.

**Comment by DRSchlaubi** [comment]
> I face the same issue when I try to play a Spotify playlist or music.

I assume all the regular expressions expect Latin characters. According to StackOverflow, this should do it `[^\x00-\x7F]`

**Comment by topi314** [comment]
this should now be fixed in v4 https://github.com/topi314/LavaSrc/commit/575db18c8ee27b1228b9144216f2b052e893ee8f and v3 https://github.com/topi314/LavaSrc/commit/934a1a5071838cb70096c2e2f93b7869f52bcc3c

**Comment by topi314** [comment]
this has finally been released in https://github.com/topi314/LavaSrc/releases/tag/4.0.0-beta.8 and https://github.com/topi314/LavaSrc/releases/tag/3.2.10
