### ISSUE TITLE
deezer not readable tracks errors

### ISSUE THREAD

**Issue by ByAhri** [topi314/LavaSrc#128]
could deezer provider be ignored if the tracks is not readable so it would search with the provider set bellow? because it's only throwing error and refusing to try the second provider

**Comment by topi314** [comment]
can you give me an example?

**Comment by ByAhri** [comment]
![image](https://github.com/topi314/LavaSrc/assets/93876720/de8d5032-6907-446f-a7f3-6235fa181267)
with this track https://www.deezer.com/en/track/2286322317
I tested using deezer api and the track in fact is not readable and the available countries are [],
but it's only throwing.

these are the providers I set, I also tested dzsearch and it's the same result, I tried ytmsearch and ytm can be played.
I thought it would search using the second provider
![image](https://github.com/topi314/LavaSrc/assets/93876720/6b8aa4d5-3165-4692-af10-5201517c0f72)

**Comment by ByAhri** [comment]
im using version 3.2.9 btw. I tested some prev versions too

**Comment by topi314** [comment]
can you send the whole stacktrace?
that's what I need aswell

**Comment by ByAhri** [comment]
here just in case too https://srcb.in/m13L5ohNGx
is this enough or should I send something else?

`2023-10-17 12:56:03.885  INFO 27840 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.deezer.com/en/track/2286322317"
2023-10-17 12:56:04.227 ERROR 27840 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Load failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This track is not readable. Available countries: []
        at com.github.topisenpai.lavasrc.deezer.DeezerAudioSourceManager.parseTrack(DeezerAudioSourceManager.java:138) ~[jar:file:C:\Users\yeona\Desktop\botss\zLavalink2\.\plugins\lavasrc-plugin-3.2.9.jar!/:na]    
        at com.github.topisenpai.lavasrc.deezer.DeezerAudioSourceManager.getTrack(DeezerAudioSourceManager.java:185) ~[jar:file:C:\Users\yeona\Desktop\botss\zLavalink2\.\plugins\lavasrc-plugin-3.2.9.jar!/:na]      
        at com.github.topisenpai.lavasrc.deezer.DeezerAudioSourceManager.loadItem(DeezerAudioSourceManager.java:100) ~[jar:file:C:\Users\yeona\Desktop\botss\zLavalink2\.\plugins\lavasrc-plugin-3.2.9.jar!/:na]      
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:428) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:410) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:208) ~[lavaplayer-1.5.0.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.5.0
  os.arch: amd64
  os.name: Windows 11
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 21
  java.runtime.version: 21+35-LTS-2513
  java.vm.version: 21+35-LTS-2513

2023-10-17 12:56:04.428  INFO 27840 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://soundcloud.com/emaahri/fetish-ariana-grande-ftdrake-ai-cover"
2023-10-17 12:56:04.429  INFO 27840 --- [ader-2-thread-1] c.s.d.l.s.s.SoundCloudClientIdTracker    : Updating SoundCloud client ID (current is null).
2023-10-17 12:56:05.204  INFO 27840 --- [ader-2-thread-1] c.s.d.l.s.s.SoundCloudClientIdTracker    : Updating SoundCloud client ID succeeded, new ID is 2PhL7PbBwZicW5x6PIIjYnUc8Az1AO9O.
2023-10-17 12:56:05.529  INFO 27840 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track Fetish -  Ariana Grande ft.drake (AI Cover)
2023-10-17 12:56:05.543  INFO 27840 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.deezer.com/en/track/2286322317"
2023-10-17 12:56:05.657  INFO 27840 --- [  XNIO-1 I/O-24] lavalink.server.io.SocketServer          : {"op":"voiceUpdate","guildId":"980636143190147072","sessionId":"7f5895ef6ecb3a1238958a42a8050f41","event":{"token":"c7004769e27634ac","guild_id":"980636143190147072","endpoint":"atlanta2242.discord.media:443"}}
2023-10-17 12:56:05.721 ERROR 27840 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Load failed

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This track is not readable. Available countries: []
        at com.github.topisenpai.lavasrc.deezer.DeezerAudioSourceManager.parseTrack(DeezerAudioSourceManager.java:138) ~[jar:file:C:\Users\yeona\Desktop\botss\zLavalink2\.\plugins\lavasrc-plugin-3.2.9.jar!/:na]    
        at com.github.topisenpai.lavasrc.deezer.DeezerAudioSourceManager.getTrack(DeezerAudioSourceManager.java:185) ~[jar:file:C:\Users\yeona\Desktop\botss\zLavalink2\.\plugins\lavasrc-plugin-3.2.9.jar!/:na]      
        at com.github.topisenpai.lavasrc.deezer.DeezerAudioSourceManager.loadItem(DeezerAudioSourceManager.java:100) ~[jar:file:C:\Users\yeona\Desktop\botss\zLavalink2\.\plugins\lavasrc-plugin-3.2.9.jar!/:na]      
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:428) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:410) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:208) ~[lavaplayer-1.5.0.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.5.0
  os.arch: amd64
  os.name: Windows 11
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 21
  java.runtime.version: 21+35-LTS-2513
  java.vm.version: 21+35-LTS-2513
`

**Comment by topi314** [comment]
I am not sure what your issue is about now, because I interpreted it as such when you play a spotify song and it tries to resolve from deezer and the tack is unplayable there, it should try the next provider right?

but this is just you loading a deezer track directly.

so what is it about now?

**Comment by ByAhri** [comment]
it happens when I do a spotify search with this track and tries to resolve from deezer too. my issue is that when the deezer track fails to load it doesn't try the next provider. I had this error originally with this track on spotify. but either way it just throws the error and the next provider is not being used. I hope this explains my issue.
here is loading the spotify link https://srcb.in/DQNtxLGQ5V

**Comment by topi314** [comment]
yes that's the log I wanted, the other is unrelated and expected

**Comment by ByAhri** [comment]
deezer only it's like a separate issue that I have and that ill have to look into myself cause it uses deezer directly, but I just sent you when I was trying to use spotify

**Comment by topi314** [comment]
can you check if https://github.com/topi314/LavaSrc/commit/6e204a5787c484dff71140dc17c3594dedfe21d3 fixes the issue?

**Comment by ByAhri** [comment]
i tried but it's giving me error compiling the project

**Comment by topi314** [comment]
why are you compiling the project? every commit gets built by github and pushed into my maven repo...

**Comment by ByAhri** [comment]
im sorry i dind't know, i went there and downloaded it. it fixed the issue with the provider. it's still logging the whole stacktrace but it's using the next provider perfectly thank u so much

**Comment by topi314** [comment]
will be in next release then

**Comment by topi314** [comment]
also fixed in v4 (master) https://github.com/topi314/LavaSrc/commit/c9c133bb4c5a48a6cee0de49b65219b72842e999

**Comment by topi314** [comment]
this has finally been released in https://github.com/topi314/LavaSrc/releases/tag/4.0.0-beta.8
