### ISSUE TITLE
Issue download 4.1.0 lavasrc

### ISSUE THREAD

**Issue by OxydeDev1789** [topi314/LavaSrc#190]
Hello from my application.yml - dependency: com.github.topi314.lavasrc:lavasrc-plugin:4.1.0

the latter puts an error like he can't download it or did you find it can you help me

**Comment by topi314** [comment]
Can you show what error you get?

**Comment by OxydeDev1789** [comment]
![9EOXksw](https://github.com/topi314/LavaSrc/assets/157843247/08d5a93c-8a33-43c9-bd73-2104eaaa83a4)
![LBwyOYA](https://github.com/topi314/LavaSrc/assets/157843247/19fa0665-7eee-40be-a0af-fbc55688cf1d)

Here are the errors

**Comment by OxydeDev1789** [comment]
Despite several attempts I did not succeed and the same for my dev friends

**Comment by topi314** [comment]
I need the full log, else I am not able to help
Just copy paste it screenshots are awful to look at

**Comment by OxydeDev1789** [comment]
2024-05-10T12:46:27.757Z ERROR 34 --- [           main] o.s.boot.SpringApplication               : Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'lavaSrcPlugin' defined in URL [jar:file:/home/container/./plugins/lavasrc-plugin-4.1.0.jar!/com/github/topi314/lavasrc/plugin/LavaSrcPlugin.class]: Failed to instantiate [com.github.topi314.lavasrc.plugin.LavaSrcPlugin]: Constructor threw exception
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:326) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:314) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:941) ~[spring-context-6.0.9.jar!/:6.0.9]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608) ~[spring-context-6.0.9.jar!/:6.0.9]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.1.0.jar!/:3.1.0]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:733) ~[spring-boot-3.1.0.jar!/:3.1.0]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:435) ~[spring-boot-3.1.0.jar!/:3.1.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) ~[spring-boot-3.1.0.jar!/:3.1.0]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:150) ~[spring-boot-3.1.0.jar!/:3.1.0]
        at lavalink.server.Launcher.launchMain(Launcher.kt:164) ~[classes!/:c1ff05db1045c793764ebdff6e6c8e9bf2d6aaec-SNAPSHOT]
        at lavalink.server.Launcher.main(Launcher.kt:126) ~[classes!/:c1ff05db1045c793764ebdff6e6c8e9bf2d6aaec-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[Lavalink.jar:c1ff05db1045c793764ebdff6e6c8e9bf2d6aaec-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[Lavalink.jar:c1ff05db1045c793764ebdff6e6c8e9bf2d6aaec-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[Lavalink.jar:c1ff05db1045c793764ebdff6e6c8e9bf2d6aaec-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[Lavalink.jar:c1ff05db1045c793764ebdff6e6c8e9bf2d6aaec-SNAPSHOT]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.topi314.lavasrc.plugin.LavaSrcPlugin]: Constructor threw exception
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:110) ~[spring-beans-6.0.9.jar!/:6.0.9]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:323) ~[spring-beans-6.0.9.jar!/:6.0.9]
        ... 27 common frames omitted
Caused by: java.lang.IllegalStateException: Youtube LavaSearch requires either Lavaplayer Youtube or Youtube Source plugin to be enabled.
        at com.github.topi314.lavasrc.plugin.LavaSrcPlugin.<init>(LavaSrcPlugin.java:81) ~[na:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[na:na]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211) ~[spring-beans-6.0.9.jar!/:6.0.9]
        ... 29 common frames omitted

**Comment by topi314** [comment]
So did you 
> Youtube LavaSearch requires either Lavaplayer Youtube or Youtube Source plugin to be enabled.

**Comment by OxydeDev1789** [comment]
I managed to install
