### ISSUE TITLE
TrackNotFoundException

### ISSUE THREAD

**Issue by 0Unzen** [topi314/LavaSrc#228]
I haven't been able to play Spotify links for about a week now. I always get:
com.github.topi314.lavasrc.mirror.TrackNotFoundException: No mirror found for track
its only on spotify urls youtube url works.

lavalink-4.0.8
youtube-plugin-1.8.3.jar
lavasrc-plugin-4.3.0.jar
use oauth

what could that be?

**Comment by topi314** [comment]
Send your `application.yml`
Does YouTube search work for you?

**Comment by 0Unzen** [comment]
YouTube Search is working.

`server:
  port: 8081
  address: 0.0.0.0
plugins:
  youtube:
    enabled: true
    oauth:
      # setting "enabled: true" is the bare minimum to get OAuth working.
      enabled: true

      # if you have a refresh token, you may set it below (make sure to uncomment the line to apply it).
      # setting a valid refresh token will skip the OAuth flow entirely. See above note on how to retrieve
      # your refreshToken.
      refreshToken: "REMOVED THIS"

      # Set this if you don't want the OAuth flow to be triggered, if you intend to supply a refresh token later.
      # Initialization is skipped automatically if a valid refresh token is supplied. Leave this commented if you're
      # completing the OAuth flow for the first time/do not have a refresh token.
      # skipInitialization: true
    allowSearch: true # Whether "ytsearch:" and "ytmsearch:" can be used.
    allowDirectVideoIds: true # Whether just video IDs can match. If false, only complete URLs will be loaded.
    allowDirectPlaylistIds: true # Whether just playlist IDs can match. If false, only complete URLs will be loaded.
    # The clients to use for track loading. See below for a list of valid clients.
    # Clients are queried in the order they are given (so the first client is queried first and so on...)
    clients:
      - MUSIC
      - ANDROID_TESTSUITE
      - WEB
      - TVHTML5EMBEDDED
  lavasrc:
    providers: # Custom providers for track loading. This is the default
      # - "dzisrc:%ISRC%" # Deezer ISRC provider
      # - "dzsearch:%QUERY%" # Deezer search provider
      - "ytsearch:\"%ISRC%\"" # Will be ignored if track does not have an ISRC. See https://en.wikipedia.org/wiki/International_Standard_Recording_Code
      - "ytsearch:%QUERY%" # Will be used if track has no ISRC or no track could be found for the ISRC
      #  you can add multiple other fallback sources here
    sources:
      spotify: true # Enable Spotify source
      applemusic: false # Enable Apple Music source
      deezer: false # Enable Deezer source
      yandexmusic: false # Enable Yandex Music source
      flowerytts: false # Enable Flowery TTS source
      youtube: false # Enable YouTube search source (https://github.com/topi314/LavaSearch)
    lyrics-sources:
      spotify: false # Enable Spotify lyrics source
      deezer: false # Enable Deezer lyrics source
      youtube: false # Enable YouTube lyrics source
      yandexmusic: false # Enable Yandex Music lyrics source
    spotify:
      clientId: "REMOVED THIS"
      clientSecret: "REMOVED THIS"
      #spDc: "AQDe_OU6qOUO9iM81TIOlKaSxnhJaWt-FI5NutvKvQZewosac7EmXICUOTN4Xf_ZAfueEeR0uchdS8dXrMM-uThiDASJ-gyIRgMJnsn0TEu8lNhTORK6pqtC_51uv4ND5S1fIhb8e73XwHrSIgnhBqYBuvmsAW5Cuhz0FA4w6a9sffDBpz0AeKmWJnFGiddlfoQGo53WOkP-cEf2D-s4ZMNk3z15" # the sp dc cookie used for accessing the spotify lyrics api
      countryCode: "DE" # the country code you want to use for filtering the artists top tracks. See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
      playlistLoadLimit: 6 # The number of pages at 100 tracks each
      albumLoadLimit: 6 # The number of pages at 50 tracks each
      resolveArtistsInSearch: true # Whether to resolve artists in track search results (can be slow)
      localFiles: false # Enable local files support with Spotify playlists. Please note `uri` & `isrc` will be `null` & `identifier` will be `"local"`
    applemusic:
      countryCode: "US" # the country code you want to use for filtering the artists top tracks and language. See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
      mediaAPIToken: "your apple music api token" # apple music api token
      # or specify an apple music key
      keyID: "your key id"
      teamID: "your team id"
      musicKitKey: |
        -----BEGIN PRIVATE KEY-----
        your key
        -----END PRIVATE KEY-----      
      playlistLoadLimit: 6 # The number of pages at 300 tracks each
      albumLoadLimit: 6 # The number of pages at 300 tracks each
    deezer:
      masterDecryptionKey: "your master decryption key" # the master key used for decrypting the deezer tracks. (yes this is not here you need to get it from somewhere else)
      # arl: "your deezer arl" # the arl cookie used for accessing the deezer api this is optional but required for formats above MP3_128
      formats: [ "FLAC", "MP3_320", "MP3_256", "MP3_128", "MP3_64", "AAC_64" ] # the formats you want to use for the deezer tracks. "FLAC", "MP3_320", "MP3_256" & "AAC_64" are only available for premium users and require a valid arl
    yandexmusic:
      accessToken: "your access token" # the token used for accessing the yandex music api. See https://github.com/TopiSenpai/LavaSrc#yandex-music
      playlistLoadLimit: 1 # The number of pages at 100 tracks each
      albumLoadLimit: 1 # The number of pages at 50 tracks each
      artistLoadLimit: 1 # The number of pages at 10 tracks each
    flowerytts:
      voice: "default voice" # (case-sensitive) get default voice from here https://api.flowery.pw/v1/tts/voices
      translate: false # whether to translate the text to the native language of voice
      silence: 0 # the silence parameter is in milliseconds. Range is 0 to 10000. The default is 0.
      speed: 1.0 # the speed parameter is a float between 0.5 and 10. The default is 1.0. (0.5 is half speed, 2.0 is double speed, etc.)
      audioFormat: "mp3" # supported formats are: mp3, ogg_opus, ogg_vorbis, aac, wav, and flac. Default format is mp3
    youtube:
      countryCode: "DE" # the country code you want to use for searching lyrics via ISRC. See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
lavalink:
  plugins:
    # Replace VERSION with the current version as shown by the Releases tab or a long commit hash for snapshots.
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.8.3"
      snapshot: false # Set to true if you want to use a snapshot version.
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.3.0"
      repository: "https://maven.lavalink.dev/releases" # this is optional for lavalink v4.0.0-beta.5 or greater
      snapshot: false # set to true if you want to use snapshot builds (see below)
  server:
    password: "REMOVED THIS"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: true
    bufferDurationMs: 4000
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
  influx:
    enabled: false
    dbName: lavalink
    hostname: localhost
    port: 8086
    username: admin
    password: password
logging:
  file:
    path: ./logs/
  level:
    # Set this to DEBUG to enable more detailed logging. Please note that this will log probably spam your console.
    root: INFO
    # Set this to DEBUG to enable more detailed logging from Lavalink
    lavalink: DEBUG
    # Set this to TRACE to see all WebSocket messages
    lavalink.server.io.SocketContext: TRACE
    # Log all track exceptions (COMMON, SUSPICIOUS & FAULT)
    com.sedmelluq.discord.lavaplayer.tools.ExceptionTools: DEBUG

  # This will log all requests to the REST API
  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true

  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30
`

**Comment by topi314** [comment]
That looks fine to me, can you show you full logs next?

**Comment by 0Unzen** [comment]
here is the log: https://mystb.in/c205e98c0fdabdb45a

**Comment by topi314** [comment]
can you add `com.github.topi314.lavasrc.mirror: DEBUG` into your logging config and check the logs again?
from what I can tell it just doesn't find the song on youtube to play

**Comment by CookieGMVN** [comment]
Same issue here. This is what Lavalink throw before killing my player:
```
2024-10-01T16:19:39.701+07:00 ERROR 36212 --- [Lavalink] [lava-daemon-pool-info-loader-2-thread-1] c.s.d.l.p.DefaultAudioPlayerManager      : Error in loading item sprec:Chiếc Khăn Piêu Cường Seven

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.2.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:214) ~[lavaplayer-2.2.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.loadItemSync(DefaultAudioPlayerManager.java:173) ~[lavaplayer-2.2.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$loadItem$0(DefaultAudioPlayerManager.java:184) ~[lavaplayer-2.2.2.jar!/:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: java.lang.IllegalArgumentException: Illegal character in query at index 48: https://api.spotify.com/v1/recommendations?Chiếc Khăn Piêu Cường Seven
	at java.base/java.net.URI.create(URI.java:932) ~[na:na]
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:66) ~[httpclient-4.5.14.jar!/:4.5.14]
	at com.github.topi314.lavasrc.spotify.SpotifySourceManager.getJson(SpotifySourceManager.java:299) ~[lavasrc-plugin-4.3.0.jar!/:na]
	at com.github.topi314.lavasrc.spotify.SpotifySourceManager.getRecommendations(SpotifySourceManager.java:382) ~[lavasrc-plugin-4.3.0.jar!/:na]
	at com.github.topi314.lavasrc.spotify.SpotifySourceManager.loadItem(SpotifySourceManager.java:238) ~[lavasrc-plugin-4.3.0.jar!/:na]
	at com.github.topi314.lavasrc.spotify.SpotifySourceManager.loadItem(SpotifySourceManager.java:228) ~[lavasrc-plugin-4.3.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:442) ~[lavaplayer-2.2.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:423) ~[lavaplayer-2.2.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.loadItemSync(DefaultAudioPlayerManager.java:154) ~[lavaplayer-2.2.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.loadItemSync(DefaultAudioPlayerManager.java:167) ~[lavaplayer-2.2.2.jar!/:na]
	... 5 common frames omitted
Caused by: java.net.URISyntaxException: Illegal character in query at index 48: https://api.spotify.com/v1/recommendations?Chiếc Khăn Piêu Cường Seven
	at java.base/java.net.URI$Parser.fail(URI.java:2995) ~[na:na]
	at java.base/java.net.URI$Parser.checkChars(URI.java:3166) ~[na:na]
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3254) ~[na:na]
	at java.base/java.net.URI$Parser.parse(URI.java:3196) ~[na:na]
	at java.base/java.net.URI.<init>(URI.java:645) ~[na:na]
	at java.base/java.net.URI.create(URI.java:930) ~[na:na]
	... 14 common frames omitted

2024-10-01T16:19:39.714+07:00 ERROR 36212 --- [Lavalink] [lava-daemon-pool-playback-1-thread-1] t.l.m.DefaultMirroringAudioTrackResolver : Failed to load track from provider "sprec:Chiếc Khăn Piêu Cường Seven"!

java.util.concurrent.CompletionException: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118) ~[na:na]
	at com.github.topi314.lavasrc.mirror.MirroringAudioTrack.loadItem(MirroringAudioTrack.java:94) ~[lavasrc-plugin-4.3.0.jar!/:na]
	at com.github.topi314.lavasrc.mirror.DefaultMirroringAudioTrackResolver.apply(DefaultMirroringAudioTrackResolver.java:52) ~[lavasrc-plugin-4.3.0.jar!/:na]
	at com.github.topi314.lavasrc.mirror.DefaultMirroringAudioTrackResolver.apply(DefaultMirroringAudioTrackResolver.java:11) ~[lavasrc-plugin-4.3.0.jar!/:na]
	at com.github.topi314.lavasrc.mirror.MirroringAudioTrack.process(MirroringAudioTrack.java:43) ~[lavasrc-plugin-4.3.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[lavaplayer-2.2.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[lavaplayer-2.2.2.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.2.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:214) ~[lavaplayer-2.2.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.loadItemSync(DefaultAudioPlayerManager.java:173) ~[lavaplayer-2.2.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$loadItem$0(DefaultAudioPlayerManager.java:184) ~[lavaplayer-2.2.2.jar!/:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
	... 3 common frames omitted
Caused by: java.lang.IllegalArgumentException: Illegal character in query at index 48: https://api.spotify.com/v1/recommendations?Chiếc Khăn Piêu Cường Seven
	at java.base/java.net.URI.create(URI.java:932) ~[na:na]
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:66) ~[httpclient-4.5.14.jar!/:4.5.14]
	at com.github.topi314.lavasrc.spotify.SpotifySourceManager.getJson(SpotifySourceManager.java:299) ~[lavasrc-plugin-4.3.0.jar!/:na]
	at com.github.topi314.lavasrc.spotify.SpotifySourceManager.getRecommendations(SpotifySourceManager.java:382) ~[lavasrc-plugin-4.3.0.jar!/:na]
	at com.github.topi314.lavasrc.spotify.SpotifySourceManager.loadItem(SpotifySourceManager.java:238) ~[lavasrc-plugin-4.3.0.jar!/:na]
	at com.github.topi314.lavasrc.spotify.SpotifySourceManager.loadItem(SpotifySourceManager.java:228) ~[lavasrc-plugin-4.3.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:442) ~[lavaplayer-2.2.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:423) ~[lavaplayer-2.2.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.loadItemSync(DefaultAudioPlayerManager.java:154) ~[lavaplayer-2.2.2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.loadItemSync(DefaultAudioPlayerManager.java:167) ~[lavaplayer-2.2.2.jar!/:na]
	... 5 common frames omitted
Caused by: java.net.URISyntaxException: Illegal character in query at index 48: https://api.spotify.com/v1/recommendations?Chiếc Khăn Piêu Cường Seven
	at java.base/java.net.URI$Parser.fail(URI.java:2995) ~[na:na]
	at java.base/java.net.URI$Parser.checkChars(URI.java:3166) ~[na:na]
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3254) ~[na:na]
	at java.base/java.net.URI$Parser.parse(URI.java:3196) ~[na:na]
	at java.base/java.net.URI.<init>(URI.java:645) ~[na:na]
	at java.base/java.net.URI.create(URI.java:930) ~[na:na]
	... 14 common frames omitted

```

**Comment by 0Unzen** [comment]
here is the new log: https://mystb.in/04d20db72b4a01573b

**Comment by topi314** [comment]
I can't see the debug logs I would expect
how does your logging config look?

**Comment by 0Unzen** [comment]
i am sorry here is my application.yml -> https://mystb.in/3d177d5a56d135075c
don't get any new debug output -> https://mystb.in/274f378af98173b88d

**Comment by topi314** [comment]
no you get 2 new interesting debug logs:
```
2024-10-01T21:30:35.777+02:00 DEBUG 211730 --- [Lavalink] [lava-daemon-pool-info-loader-2-thread-1] c.g.t.l.mirror.MirroringAudioTrack       : No matches found for: ytsearch:"QMFMG2368110"
2024-10-01T21:30:36.134+02:00 DEBUG 211730 --- [Lavalink] [lava-daemon-pool-info-loader-2-thread-1] c.g.t.l.mirror.MirroringAudioTrack       : No matches found for: ytsearch:Heroes Are Calling Smash Into Pieces
```

can you try loading `ytsearch:Heroes Are Calling Smash Into Pieces`?

**Comment by 0Unzen** [comment]
I'm a little confused the log already says "No matches found for: ytsearch:Heroes Are Calling Smash Into Pieces" for me

**Comment by topi314** [comment]
anyway, since this is an issue with youtube and not lavasrc I am gonna close this.
you can configure other providers such as deezer to resolve spotify tracks or get your youtube working

**Comment by 0Unzen** [comment]
thanks for youre help got it -> https://github.com/lavalink-devs/youtube-source/issues/58
