### ISSUE TITLE
java.lang.IllegalStateException: Mp3 frame not found. (Deezer)

### ISSUE THREAD

**Issue by sawa-ko** [topi314/LavaSrc#232]
Song URL: `https://www.deezer.com/mx/track/13188546`

```yml
lavalink:
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.3.0"
      snapshot: false
```

```
2024-10-26T16:52:14.942Z  INFO 13989 --- [Lavalink] [           main] lavalink.server.Launcher                 : Starting Launcher v4.0.8 using Java 23.0.1 with PID 13989 (/root/Lavalink.jar started by root in /root)
2024-10-26T16:52:14.946Z  INFO 13989 --- [Lavalink] [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2024-10-26T16:52:15.548Z  INFO 13989 --- [Lavalink] [           main] l.server.bootstrap.PluginManager         : Found plugin 'youtube-plugin' version 1.8.3
2024-10-26T16:52:15.549Z  INFO 13989 --- [Lavalink] [           main] l.server.bootstrap.PluginManager         : Found plugin 'lavasrc-plugin' version 4.3.0
2024-10-26T16:52:15.549Z  INFO 13989 --- [Lavalink] [           main] l.server.bootstrap.PluginManager         : Found plugin 'sponsorblock-plugin' version 3.0.1
2024-10-26T16:52:15.565Z  INFO 13989 --- [Lavalink] [           main] l.server.bootstrap.PluginManager         : Loaded youtube-plugin-1.8.3.jar (16 classes)
2024-10-26T16:52:15.640Z  INFO 13989 --- [Lavalink] [           main] l.server.bootstrap.PluginManager         : Loaded lavasrc-plugin-4.3.0.jar (168 classes)
2024-10-26T16:52:15.671Z  INFO 13989 --- [Lavalink] [           main] l.server.bootstrap.PluginManager         : Loaded sponsorblock-plugin-3.0.1.jar (90 classes)
2024-10-26T16:52:15.790Z  INFO 13989 --- [Lavalink] [           main] lavalink.server.Launcher                 : Started Launcher in 1.112 seconds (process running for 1.424)
2024-10-26T16:52:15.830Z  INFO 13989 --- [Lavalink] [           main] lavalink.server.Launcher                 : 

       .   _                  _ _       _    __ _ _
      /\\ | | __ ___   ____ _| (_)_ __ | | __\ \ \ \
     ( ( )| |/ _` \ \ / / _` | | | '_ \| |/ / \ \ \ \
      \\/ | | (_| |\ V / (_| | | | | | |   <   ) ) ) )
       '  |_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\ / / / /
    =========================================/_/_/_/

        Version:        4.0.8
        Build time:     20.09.2024 20:20:10 UTC
        Branch          HEAD
        Commit:         2946608
        Commit time:    20.09.2024 20:17:58 UTC
        JVM:            23.0.1
        Lavaplayer      2.2.2

2024-10-26T16:52:15.835Z  INFO 13989 --- [Lavalink] [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
2024-10-26T16:52:16.253Z  WARN 13989 --- [Lavalink] [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2024-10-26T16:52:16.268Z  INFO 13989 --- [Lavalink] [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2024-10-26T16:52:16.269Z  INFO 13989 --- [Lavalink] [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 430 ms
2024-10-26T16:52:16.910Z  INFO 13989 --- [Lavalink] [           main] c.g.t.lavasrc.plugin.LavaSrcPlugin       : Loading LavaSrc plugin...
2024-10-26T16:52:16.936Z  INFO 13989 --- [Lavalink] [           main] c.g.t.lavasrc.plugin.LavaSrcPlugin       : Registering Youtube Source audio source manager...
2024-10-26T16:52:16.946Z  INFO 13989 --- [Lavalink] [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
2024-10-26T16:52:17.069Z  WARN 13989 --- [Lavalink] [           main] d.l.youtube.plugin.YoutubePluginLoader   : youtubeConfig missing or 'clients' was not specified, default values will be used.
2024-10-26T16:52:17.091Z  INFO 13989 --- [Lavalink] [           main] d.l.youtube.plugin.YoutubePluginLoader   : YouTube source initialised with clients: WEB_REMIX, WEB, ANDROID_TESTSUITE, TVHTML5_SIMPLY_EMBEDDED_PLAYER 
2024-10-26T16:52:17.160Z  INFO 13989 --- [Lavalink] [           main] d.l.youtube.http.YoutubeOauth2Handler    : YouTube access token refreshed successfully
2024-10-26T16:52:17.161Z  INFO 13989 --- [Lavalink] [           main] c.g.t.lavasrc.plugin.LavaSrcPlugin       : Registering Spotify audio source manager...
2024-10-26T16:52:17.161Z  INFO 13989 --- [Lavalink] [           main] c.g.t.lavasrc.plugin.LavaSrcPlugin       : Registering Deezer audio source manager...
2024-10-26T16:52:17.166Z  INFO 13989 --- [Lavalink] [           main] c.g.t.s.plugin.SponsorBlockPlugin        : Loading SponsorBlock Plugin...
2024-10-26T16:52:17.247Z  INFO 13989 --- [Lavalink] [           main] l.server.config.KoeConfiguration         : OS: LINUX, Arch: X86_64
2024-10-26T16:52:17.247Z  INFO 13989 --- [Lavalink] [           main] l.server.config.KoeConfiguration         : Enabling JDA-NAS
2024-10-26T16:52:17.249Z  INFO 13989 --- [Lavalink] [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: loading with filter null
2024-10-26T16:52:17.252Z  INFO 13989 --- [Lavalink] [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: successfully loaded.
2024-10-26T16:52:17.269Z  WARN 13989 --- [Lavalink] [           main] l.server.config.SentryConfiguration      : Turning off sentry
2024-10-26T16:52:17.461Z  INFO 13989 --- [Lavalink] [           main] io.undertow                              : starting server: Undertow - 2.3.13.Final
2024-10-26T16:52:17.467Z  INFO 13989 --- [Lavalink] [           main] org.xnio                                 : XNIO version 3.8.8.Final
2024-10-26T16:52:17.474Z  INFO 13989 --- [Lavalink] [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.8.8.Final
2024-10-26T16:52:17.538Z  INFO 13989 --- [Lavalink] [           main] org.jboss.threads                        : JBoss Threads version 3.5.0.Final
2024-10-26T16:52:17.574Z  INFO 13989 --- [Lavalink] [           main] o.s.b.w.e.undertow.UndertowWebServer     : Undertow started on port 2333 (http) with context path '/'
2024-10-26T16:52:17.577Z  INFO 13989 --- [Lavalink] [           main] lavalink.server.Launcher                 : Started Launcher in 1.783 seconds (process running for 3.212)
2024-10-26T16:52:17.578Z  INFO 13989 --- [Lavalink] [           main] lavalink.server.Launcher                 : Lavalink is ready to accept connections.
```

```
2024-10-26T16:49:12.849Z  INFO 13915 --- [Lavalink] [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.deezer.com/mx/track/13188546?host=0&utm_campaign=clipboard-generic&utm_source=user_sharing&utm_content=track-13188546&deferredFl=1"
2024-10-26T16:49:13.022Z  INFO 13915 --- [Lavalink] [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Loaded track Atrévete-Te-Te
2024-10-26T16:49:13.030Z  INFO 13915 --- [Lavalink] [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=https%3A%2F%2Fwww.deezer.com%2Fmx%2Ftrack%2F13188546%3Fhost%3D0%26utm_campaign%3Dclipboard-generic%26utm_source%3Duser_sharing%26utm_content%3Dtrack-13188546%26deferredFl%3D1
2024-10-26T16:49:13.226Z  INFO 13915 --- [Lavalink] [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/x/players/x?noReplace=false, payload={"track":{"encoded":"QAACwgMAD0F0csOpdmV0ZS1UZS1UZQAIQ2FsbGUgMTMAAAAAAAOlmAAIMTMxODg1NDYAAQAhaHR0cHM6Ly9kZWV6ZXIuY29tL3RyYWNrLzEzMTg4NTQ2AQBpaHR0cHM6Ly9lLWNkbnMtaW1hZ2VzLmR6Y2RuLm5ldC9pbWFnZXMvY292ZXIvNTZmNGM3Y2I5MjllODc0OTIwN2QwYzA2ZDliOWJhMTkvMTAwMHgxMDAwLTAwMDAwMC04MC0wLTAuanBnAQAMVVMzSDMwNTAwMjA5AAZkZWV6ZXIBABtDYWxsZSAxMyAoRXhwbGljaXQgVmVyc2lvbikBACRodHRwczovL3d3dy5kZWV6ZXIuY29tL2FsYnVtLzEyMDk1MjMBACFodHRwczovL3d3dy5kZWV6ZXIuY29tL2FydGlzdC8xMTEBAGpodHRwczovL2UtY2Rucy1pbWFnZXMuZHpjZG4ubmV0L2ltYWdlcy9hcnRpc3QvNGI0YWY4ZmVjNmY0ZWUxYmQwMWI3OGZkOGRlYzJlN2MvMTAwMHgxMDAwLTAwMDAwMC04MC0wLTAuanBnAQEKaHR0cHM6Ly9jZG50LXByZXZpZXcuZHpjZG4ubmV0L2FwaS8xLzEvNC85LzgvMC80OThkMGMwODJjNjUwZTEzYWExMDZlY2VlNzRlNjQ0Zi5tcDM/aGRuZWE9ZXhwPTE3Mjk5NjIyNTJ+YWNsPS9hcGkvMS8xLzQvOS84LzAvNDk4ZDBjMDgyYzY1MGUxM2FhMTA2ZWNlZTc0ZTY0NGYubXAzKn5kYXRhPXVzZXJfaWQ9MCxhcHBsaWNhdGlvbl9pZD00Mn5obWFjPTU0MjgzMTQ5MTMzNTA1YzRiMWM0ZTI3M2YwNjM2M2ZkZDRhOGNlYzY1MjFiMDM0YmFiNWYyYjM4OGU0ZDdhNjEAAAAAAAAAAAA=","userData":{"requester_id":x}}}
2024-10-26T16:49:14.134Z  INFO 13915 --- [Lavalink] [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library libmpg123-0: loading with filter com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader$$Lambda/0x00007230c3807540@1141ca5c
2024-10-26T16:49:14.134Z  INFO 13915 --- [Lavalink] [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library connector: loading with filter null
2024-10-26T16:49:14.148Z  INFO 13915 --- [Lavalink] [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library connector: successfully loaded.
2024-10-26T16:49:14.200Z ERROR 13915 --- [Lavalink] [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of 13188546

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[lavaplayer-2.2.2.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[na:na]
Caused by: java.lang.IllegalStateException: Mp3 frame not found.
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3FrameReader.runFrameScanLoop(Mp3FrameReader.java:76) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3FrameReader.scanForFrame(Mp3FrameReader.java:53) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.parseHeaders(Mp3TrackProvider.java:80) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3AudioTrack.process(Mp3AudioTrack.java:33) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-2.2.2.jar!/:na]
        at com.github.topi314.lavasrc.deezer.DeezerAudioTrack.process(DeezerAudioTrack.java:156) ~[lavasrc-plugin-4.3.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[lavaplayer-2.2.2.jar!/:na]
        ... 4 common frames omitted
```

**Comment by topi314** [comment]
See: https://github.com/topi314/LavaSrc/discussions/118
