### ISSUE TITLE
Problem with play track

### ISSUE THREAD

**Issue by realdarek** [topi314/LavaSrc#233]
2024-10-30T14:42:39.377+01:00  INFO 23216 --- [Lavalink] [  XNIO-1 task-2] lavalink.server.io.SocketServer          : Connection successfully established from Magmastream
2024-10-30T14:42:39.427+01:00  INFO 23216 --- [Lavalink] [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /v4/info, client=127.0.0.1, headers=[Authorization:"nopass", Accept:"application/json, text/plain, */*", Connection:"keep-alive", User-Agent:"axios/1.7.7", Host:"127.0.0.1:2333", Accept-Encoding:"gzip, compress, deflate, br", Content-Type:"application/json;charset=UTF-8"]
2024-10-30T14:42:39.457+01:00  INFO 23216 --- [Lavalink] [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/dcmxghcm0k43a1zr, client=127.0.0.1, headers=[Authorization:"nopass", Accept:"application/json, text/plain, */*", Connection:"keep-alive", User-Agent:"axios/1.7.7", Host:"127.0.0.1:2333", Accept-Encoding:"gzip, compress, deflate, br", Content-Length:"32", Content-Type:"application/json;charset=UTF-8"], payload={"resuming":true,"timeout":1000}
2024-10-30T14:42:40.874+01:00  INFO 23216 --- [Lavalink] [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://deezer.page.link/9cJnWJzCK2tcSD9o8"
2024-10-30T14:42:41.459+01:00  INFO 23216 --- [Lavalink] [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Loaded track Happier Than Ever
2024-10-30T14:42:41.478+01:00  INFO 23216 --- [Lavalink] [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=https%3A%2F%2Fdeezer.page.link%2F9cJnWJzCK2tcSD9o8, client=127.0.0.1, headers=[Authorization:"nopass", Accept:"application/json, text/plain, */*", Connection:"keep-alive", User-Agent:"axios/1.7.7", Host:"127.0.0.1:2333", Accept-Encoding:"gzip, compress, deflate, br", Content-Type:"application/json;charset=UTF-8"]
2024-10-30T14:42:41.535+01:00  INFO 23216 --- [Lavalink] [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/dcmxghcm0k43a1zr/players/1296927000836968568?noReplace=false, client=127.0.0.1, headers=[Authorization:"nopass", Accept:"application/json, text/plain, */*", Connection:"keep-alive", User-Agent:"axios/1.7.7", Host:"127.0.0.1:2333", Accept-Encoding:"gzip, compress, deflate, br", Content-Length:"14", Content-Type:"application/json;charset=UTF-8"], payload={"volume":100}
2024-10-30T14:42:41.535+01:00  INFO 23216 --- [Lavalink] [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/dcmxghcm0k43a1zr/players/1296927000836968568?noReplace=false, client=127.0.0.1, headers=[Authorization:"nopass", Accept:"application/json, text/plain, */*", Connection:"keep-alive", User-Agent:"axios/1.7.7", Host:"127.0.0.1:2333", Accept-Encoding:"gzip, compress, deflate, br", Content-Length:"975", Content-Type:"application/json;charset=UTF-8"], payload={"encodedTrack":"QAACyQMAEUhhcHBpZXIgVGhhbiBFdmVyAA1CaWxsaWUgRWlsaXNoAAAAAAAEjBAACjE0NDk3NDA1OTIAAQAjaHR0cHM6Ly9kZWV6ZXIuY29tL3RyYWNrLzE0NDk3NDA1OTIBAGlodHRwczovL2UtY2Rucy1pbWFnZXMuZHpjZG4ubmV0L2ltYWdlcy9jb3Zlci9iYjI4ODA1NDhkZDNiYzcxZmI5N2RlZjJlZWRlYzEzMC8xMDAweDEwMDAtMDAwMDAwLTgwLTAtMC5qcGcBAAxVU1VNNzIxMDU5MzYABmRlZXplcgEAEUhhcHBpZXIgVGhhbiBFdmVyAQAmaHR0cHM6Ly93d3cuZGVlemVyLmNvbS9hbGJ1bS8yNDgyMTY2MjIBACVodHRwczovL3d3dy5kZWV6ZXIuY29tL2FydGlzdC85NjM1NjI0AQBqaHR0cHM6Ly9lLWNkbnMtaW1hZ2VzLmR6Y2RuLm5ldC9pbWFnZXMvYXJ0aXN0LzhlYWIxYTlhNjQ0ODg5YWFiYWNhMWUxOTNlMDVmOTg0LzEwMDB4MTAwMC0wMDAwMDAtODAtMC0wLmpwZwEBCmh0dHBzOi8vY2RudC1wcmV2aWV3LmR6Y2RuLm5ldC9hcGkvMS8xL2UvYy8xLzAvZWMxN2IwMzRiOGIyNWY1YjlkNTFkNDY3ODc0MzE2ZGIubXAzP2hkbmVhPWV4cD0xNzMwMjk2NjYwfmFjbD0vYXBpLzEvMS9lL2MvMS8wL2VjMTdiMDM0YjhiMjVmNWI5ZDUxZDQ2Nzg3NDMxNmRiLm1wMyp+ZGF0YT11c2VyX2lkPTAsYXBwbGljYXRpb25faWQ9NDJ+aG1hYz00MzEwZDU5NmYzZGY0MTRmNTcwMGVlZTA4YzhmOWM3MzVmNzY0OGI0M2JlNGI3NzVjYjZhNDkxOWYyZmI1ZTUzAAAAAAAAAAAA"}
2024-10-30T14:42:41.891+01:00  INFO 23216 --- [Lavalink] [  XNIO-1 task-3] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/dcmxghcm0k43a1zr/players/1296927000836968568?noReplace=false, client=127.0.0.1, headers=[Authorization:"nopass", Accept:"application/json, text/plain, */*", Connection:"keep-alive", User-Agent:"axios/1.7.7", Host:"127.0.0.1:2333", Accept-Encoding:"gzip, compress, deflate, br", Content-Length:"128", Content-Type:"application/json;charset=UTF-8"], payload={"voice":{"token":"b9135286092f8931","endpoint":"warsaw10017.discord.media:443","sessionId":"9b7131f1ad9908b2cb01d91ff13cd6af"}}
2024-10-30T14:42:42.016+01:00  INFO 23216 --- [Lavalink] [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library libmpg123-0: loading with filter com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader$$Lambda/0x000002d61a855000@5b5a3459
2024-10-30T14:42:42.049+01:00  INFO 23216 --- [Lavalink] [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library libmpg123-0: successfully loaded.
2024-10-30T14:42:42.050+01:00  INFO 23216 --- [Lavalink] [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library connector: loading with filter null
2024-10-30T14:42:42.096+01:00  INFO 23216 --- [Lavalink] [back-1-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library connector: successfully loaded.
2024-10-30T14:42:42.137+01:00 ERROR 23216 --- [Lavalink] [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of 1449740592

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[lavaplayer-2.2.2.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[na:na]
Caused by: java.lang.IllegalStateException: Mp3 frame not found.
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3FrameReader.runFrameScanLoop(Mp3FrameReader.java:76) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3FrameReader.scanForFrame(Mp3FrameReader.java:53) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.parseHeaders(Mp3TrackProvider.java:80) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3AudioTrack.process(Mp3AudioTrack.java:33) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-2.2.2.jar!/:na]
        at com.github.topi314.lavasrc.deezer.DeezerAudioTrack.process(DeezerAudioTrack.java:102) ~[jar:file:C:\Users\pawli\Desktop\dbitbot\lavalink\.\plugins\lavasrc-plugin-4.1.1.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[lavaplayer-2.2.2.jar!/:na]
        ... 4 common frames omitted

**Comment by topi314** [comment]
duplicate of: https://github.com/topi314/LavaSrc/discussions/118
