### ISSUE TITLE
Something went wrong when decoding the track.

### ISSUE THREAD

**Issue by SCARTAL** [topi314/LavaSrc#239]
## Description
I have switched from YouTube to Deezer recently since I migrated I keep getting `Something went wrong when decoding the track.` error on different tracks at random times (the problem is not the tracks since it plays perfectly on the second try)

## To Reproduce
1. config and switch to deezer source (replace `ytsearch` with `dzsearch` for exp)
2. play big deezer or spotify playlist (about 20 songs)
3. Wait until it skips a song in the middle of playing
4. See the error on the lavalink server

## Expected behavior
The playlist plays with no problem till the end

## Version info
Lavalink: V4.0.8
LavaSrc: V4.3.0

Output of `java -version`:
```
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)
```

Lavalink Logs:
```
2024-11-22T08:03:20.059-08:00 ERROR 5196 --- [Lavalink] [ack-1-thread-52] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of 1811152957

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:279) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:234) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3AudioTrack.process(Mp3AudioTrack.java:36) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-2.2.2.jar!/:na]
        at com.github.topi314.lavasrc.deezer.DeezerAudioTrack.process(DeezerAudioTrack.java:156) ~[jar:file:C:\Users\Administrator\Desktop\lavalink-server\bin\.\plugins\lavasrc-plugin-4.3.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[lavaplayer-2.2.2.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.lang.RuntimeException: java.io.EOFException
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.provideFrames(Mp3TrackProvider.java:138) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:261) ~[lavaplayer-2.2.2.jar!/:na]
        ... 9 common frames omitted
Caused by: java.io.EOFException: null
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:203) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3FrameReader.fillFrameBuffer(Mp3FrameReader.java:121) ~[lavaplayer-2.2.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.provideFrames(Mp3TrackProvider.java:121) ~[lavaplayer-2.2.2.jar!/:na]
        ... 10 common frames omitted
```

**Comment by SCARTAL** [comment]
[spring.log](https://github.com/user-attachments/files/17882132/spring.log)
[application - Copy.txt](https://github.com/user-attachments/files/17882133/application.-.Copy.txt)

**Comment by topi314** [comment]
nothing I can reproduce, if this doesn't happen all the time just ignore it
