### ISSUE TITLE
Deezer Failed to get media URL: 2000: An error occurred while decoding track token.

### ISSUE THREAD

**Issue by flav-code** [topi314/LavaSrc#95]
# version
LavaSrc: 4.0.0-beta.3
Lavalink: 4.0.0-beta.3
Java: 17

it happens randomly and I can't reproduce it, so if you test it the link will probably work.

```
{
   op: 'event',
   type: 'TrackExceptionEvent',
   guildId: '-------------', // i removed the id
   track: {
     encoded: 'QAAA2QMACE91ciBTb25nAAxUYXlsb3IgU3dpZnQAAAAAAAMRKAAHMjI4MjQ5NAABACBodHRwczovL2RlZXplci5jb20vdHJhY2svMjI4MjQ5NAEAaWh0dHBzOi8vZS1jZG5zLWltYWdlcy5kemNkbi5uZXQvaW1hZ2VzL2NvdmVyLzljMGU4MGJiM2MxNmUxYzk4N2NmMjM1OTI5ZWI3NzU3LzEwMDB4MTAwMC0wMDAwMDAtODAtMC0wLmpwZwEADFVTQ0pZMDcwMzE0MgAGZGVlemVyAAAAAAAAAAA=',
     info: {
       identifier: '2282494',
       isSeekable: true,
       author: 'Taylor Swift',
       length: 201000,
       isStream: false,
       position: 0,
       title: 'Our Song',
       uri: 'https://deezer.com/track/2282494',
       sourceName: 'deezer',
       artworkUrl: 'https: //e-cdns-images.dzcdn.net/images/cover/9c0e80bb3c16e1c987cf235929eb7757/1000x1000-000000-80-0-0.jpg',
       isrc: 'USCJY0703142'
        },
     pluginInfo: {}
    },
   exception: {
     message: 'Something broke when playing the track.',
     severity: 'fault',
     cause: 'java.lang.IllegalStateException: Failed to get media URL: 2000: An error occurred while decoding track token.'
    }
}
```

**Comment by topi314** [comment]
can you append the full stracktrace please?

**Comment by flav-code** [comment]
Nothing abnormal

![image](https://github.com/topi314/LavaSrc/assets/48295189/c66b31ea-f1d1-40b2-b010-dc37ca2977e5)

**Comment by topi314** [comment]
please paste the log as text

**Comment by flav-code** [comment]
```
2023-08-04T00:26:15.139+08:00  INFO 26815 --- [XNIO-1 task-7] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "dzisrc:USCJY0703142"
2023-08-04T00:26:15.871+08:00  INFO 26815 --- [XNIO-1 task-7] lavalink.server.player.AudioLoader       : Loaded track Our Song
2023-08-04T00:26:15.873+08:00  INFO 26815 --- [XNIO-1 task-7] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=dzisrc%3AUSCJY0703142, client=0.0.0.0
2023-08-04T00:26:16.209+08:00  INFO 26815 --- [XNIO-1 task-7] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/jpdi4y02natgnicw/players/397378255709143043?noReplace=true, client=0.0.0.0, payload={"encodedTrack":"QAAA2QMACE91ciBTb25nAAxUYXlsb3IgU3dpZnQAAAAAAAMRKAAHMjI4MjQ5NAABACBodHRwczovL2RlZXplci5jb20vdHJhY2svMjI4MjQ5NAEAaWh0dHBzOi8vZS1jZG5zLWltYWdlcy5kemNkbi5uZXQvaW1hZ2VzL2NvdmVyLzljMGU4MGJiM2MxNmUxYzk4N2NmMjM1OTI5ZWI3NzU3LzEwMDB4MTAwMC0wMDAwMDAtODAtMC0wLmpwZwEADFVTQ0pZMDcwMzE0MgAGZGVlemVyAAAAAAAAAAA="}
2023-08-04T00:26:17.121+08:00 ERROR 26815 --- [lava-daemon-pool-playback-1-thread-9] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of 2282494

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.0.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117) ~[lavaplayer-2.0.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:321) ~[lavaplayer-2.0.0.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.lang.IllegalStateException: Failed to get media URL: 2000: An error occurred while decoding track token.
	at com.github.topi314.lavasrc.deezer.DeezerAudioTrack.checkResponse(DeezerAudioTrack.java:66) ~[lavasrc-plugin-4.0.0-beta.3.jar!/:na]
	at com.github.topi314.lavasrc.deezer.DeezerAudioTrack.getTrackMediaURI(DeezerAudioTrack.java:58) ~[lavasrc-plugin-4.0.0-beta.3.jar!/:na]
	at com.github.topi314.lavasrc.deezer.DeezerAudioTrack.process(DeezerAudioTrack.java:84) ~[lavasrc-plugin-4.0.0-beta.3.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-2.0.0.jar!/:na]
	... 4 common frames omitted

```

**Comment by flav-code** [comment]
Could you unblock me ?

**Comment by jurienhamaker** [comment]
Been having the same issue "sometimes", it's very random.

**Comment by topi314** [comment]
this has absolutely nothing to do with this issue or lavasrc

**Comment by topi314** [comment]
closing this since I haven't seen any recent reports about this. feel free to reopen if this issue persists ig

**Comment by flav-code** [comment]
I still have the issue on my side
