### ISSUE TITLE
Deezer Error Invalid Character

### ISSUE THREAD

**Issue by fb-sean** [topi314/LavaSrc#96]
My whole lavalink console is full with this when I try to resolve spotify etc. Without having yt enabled.

```
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:361) ~[lavaplayer-1.4.2.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.4.2-original
  os.arch: amd64
  os.name: Linux
  os.version: 5.15.0-53-generic
  java.vendor: Oracle Corporation
  java.version: 18
  java.runtime.version: 18+36-2087
  java.vm.version: 18+36-2087
Caused by: java.util.concurrent.CompletionException: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
        at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118) ~[na:na]
        at com.github.topisenpai.lavasrc.mirror.MirroringAudioTrack.loadItem(MirroringAudioTrack.java:89) ~[lavasrc-plugin-3.2.5.jar!/:na]
        at com.github.topisenpai.lavasrc.mirror.DefaultMirroringAudioTrackResolver.apply(DefaultMirroringAudioTrackResolver.java:52) ~[lavasrc-plugin-3.2.5.jar!/:na]
        at com.github.topisenpai.lavasrc.mirror.DefaultMirroringAudioTrackResolver.apply(DefaultMirroringAudioTrackResolver.java:13) ~[lavasrc-plugin-3.2.5.jar!/:na]
        at com.github.topisenpai.lavasrc.mirror.MirroringAudioTrack.process(MirroringAudioTrack.java:44) ~[lavasrc-plugin-3.2.5.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.4.2.jar!/:na]
        ... 4 common frames omitted
Caused by: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:242) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:231) ~[lavaplayer-1.4.2.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        ... 3 common frames omitted
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.4.2-original
  os.arch: amd64
  os.name: Linux
  os.version: 5.15.0-53-generic
  java.vendor: Oracle Corporation
  java.version: 18
  java.runtime.version: 18+36-2087
  java.vm.version: 18+36-2087
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 38: https://api.deezer.com/2.0/track/isrc:"QZMER2285866"
        at java.base/java.net.URI.create(URI.java:906) ~[na:na]
        at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:66) ~[httpclient-4.5.10.jar!/:4.5.10]
        at com.github.topisenpai.lavasrc.deezer.DeezerAudioSourceManager.getJson(DeezerAudioSourceManager.java:116) ~[lavasrc-plugin-3.2.5.jar!/:na]
        at com.github.topisenpai.lavasrc.deezer.DeezerAudioSourceManager.getTrackByISRC(DeezerAudioSourceManager.java:155) ~[lavasrc-plugin-3.2.5.jar!/:na]
        at com.github.topisenpai.lavasrc.deezer.DeezerAudioSourceManager.loadItem(DeezerAudioSourceManager.java:71) ~[lavasrc-plugin-3.2.5.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:449) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:431) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:223) ~[lavaplayer-1.4.2.jar!/:na]
        ... 4 common frames omitted
Caused by: java.net.URISyntaxException: Illegal character in path at index 38: https://api.deezer.com/2.0/track/isrc:"QZMER2285866"
        at java.base/java.net.URI$Parser.fail(URI.java:2973) ~[na:na]
        at java.base/java.net.URI$Parser.checkChars(URI.java:3144) ~[na:na]
        at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3226) ~[na:na]
        at java.base/java.net.URI$Parser.parse(URI.java:3174) ~[na:na]
        at java.base/java.net.URI.<init>(URI.java:623) ~[na:na]
        at java.base/java.net.URI.create(URI.java:904) ~[na:na]
        ... 11 common frames omitted

```

I use the newest version of LavaSRC

**Comment by DRSchlaubi** [comment]
I assume the `"` should be url encoded

**Comment by fb-sean** [comment]
It shouldnt be there at all when you do the request without it in your browser you get the song

**Comment by topi314** [comment]
Then why do you include it at all on your providers

**Comment by DRSchlaubi** [comment]
They aren't in the example config https://github.com/topi314/LavaSrc#configuration, so did you change that?
