### ISSUE TITLE
Something broke when playing the track. - Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by LucasB25** [topi314/LavaSrc#98]
```
2023-08-08 19:29:26.991 ERROR 18286 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of 1sUTfgduT0WIQO8kXKXxLC

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.5.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116) ~[lavaplayer-1.5.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:346) ~[lavaplayer-1.5.0.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.5.0
  os.arch: amd64
  os.name: Linux
  os.version: 5.4.106-1-pve
  java.vendor: Private Build
  java.version: 17.0.7
  java.runtime.version: 17.0.7+7-Ubuntu-0ubuntu120.04
  java.vm.version: 17.0.7+7-Ubuntu-0ubuntu120.04
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[na:na]
	at java.base/java.util.Objects.checkIndex(Objects.java:361) ~[na:na]
	at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[na:na]
	at com.github.topisenpai.lavasrc.mirror.MirroringAudioTrack.process(MirroringAudioTrack.java:47) ~[lavasrc-plugin-3.2.5.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.5.0.jar!/:na]
	... 4 common frames omitted

```
https://srcb.in/0z1IEFcDPZ

java **17.0.7** 
lavalink  **3.7.8**
lavasrc-plugin **3.2.5**

**Comment by DRSchlaubi** [comment]
This looks like you tried playing an emtpy playlist

**Comment by LucasB25** [comment]
not possible the music is continuously automatic

**Comment by DRSchlaubi** [comment]
https://github.com/topi314/LavaSrc/blob/46e4d461ea04a3b5d928b8b5f46f8308d9b5b70c/main/src/main/java/com/github/topi314/lavasrc/mirror/MirroringAudioTrack.java#L46

**Comment by DRSchlaubi** [comment]
Okay myb looks like the resolved track resulted in an empty playlist

**Comment by LucasB25** [comment]
so it would come from my house in quotation marks?
but how to solve this?

**Comment by DRSchlaubi** [comment]
I don't know which track was exactly resolved

**Comment by LucasB25** [comment]
well neither do I, since I used autoplay

**Comment by LucasB25** [comment]
![image](https://github.com/topi314/LavaSrc/assets/50886682/c82a5f56-12cc-4415-9955-7a9367919758)
I no longer have

**Comment by topi314** [comment]
see if https://github.com/topi314/LavaSrc/commit/b8c4c7306c56c5157971ed5c1a41789956fcb1d1 fixes it

**Comment by LucasB25** [comment]
> see if [b8c4c73](https://github.com/topi314/LavaSrc/commit/b8c4c7306c56c5157971ed5c1a41789956fcb1d1) fixes it

I don’t need to update. I can test now?

**Comment by topi314** [comment]
if you update lavasrc to this commit you can test it yes

**Comment by LucasB25** [comment]
> if you update lavasrc to this commit you can test it yes

How can I do it? 'cause 'probably not the same as an npm package

**Comment by topi314** [comment]
as mentioned in the readme https://github.com/topi314/LavaSrc/tree/v3-legacy#lavalink-usage
just change the repository from `/releases` to `/snapshots` & use the first 7 char commit hash from the commit above as the version

**Comment by LucasB25** [comment]
```
payload={"encodedTrack":"QAAA3QIAC0JsdWUgT3JjaGlkABFUaGUgV2hpdGUgU3RyaXBlcwAAAAAAAmd4ABY0alU3TlBrejRIVm5NNGh3ZXFOaEkxAAEANWh0dHBzOi8vb3Blbi5zcG90aWZ5LmNvbS90cmFjay80alU3TlBrejRIVm5NNGh3ZXFOaEkxAAdzcG90aWZ5AQAMVVNWVDEwNTAwMDc2AQBAaHR0cHM6Ly9pLnNjZG4uY28vaW1hZ2UvYWI2NzYxNmQwMDAwYjI3M2U4YTFhZTU5MWJlZmU0YmIwYTkyNjFhYgAAAAAAAAAA"}
2023-08-08 21:08:34.038  INFO 19412 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://open.spotify.com/track/2CzKVfVA9U7OKbIpAVPZOk"
2023-08-08 21:08:38.262  INFO 19412 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track Sabbath Bloody Sabbath
2023-08-08 21:08:38.265  INFO 19412 --- [  XNIO-1 task-2] lavalink.server.io.RequestLoggingFilter  : GET /v3/loadtracks?identifier=https%3A%2F%2Fopen.spotify.com%2Ftrack%2F2CzKVfVA9U7OKbIpAVPZOk, client=127.0.0.1
`2023-08-08 21:08:42.734  WARN 19412 --- [ntLoopGroup-2-3] lavalink.server.player.EventEmitter      : Blue Orchid got stuck! Threshold surpassed: 10000ms`
2023-08-08 21:08:42.742  INFO 19412 --- [  XNIO-1 task-2] lavalink.server.io.RequestLoggingFilter  : PATCH /v3/sessions/8euhnj3yq3py50gy/players/639211220280541194/?noReplace=false, client=127.0.0.1, payload={"encodedTrack":null}
2023-08-08 21:08:42.751  INFO 19412 --- [  XNIO-1 task-2] lavalink.server.io.RequestLoggingFilter  : PATCH /v3/sessions/8euhnj3yq3py50gy/players/639211220280541194/?noReplace=false, client=127.0.0.1, payload={"encodedTrack":"QAAA5AIAFlNhYmJhdGggQmxvb2R5IFNhYmJhdGgADUJsYWNrIFNhYmJhdGgAAAAAAAVN6gAWMkN6S1ZmVkE5VTdPS2JJcEFWUFpPawABADVodHRwczovL29wZW4uc3BvdGlmeS5jb20vdHJhY2svMkN6S1ZmVkE5VTdPS2JJcEFWUFpPawAHc3BvdGlmeQEADEdCQUpFNzMwMDAyMgEAQGh0dHBzOi8vaS5zY2RuLmNvL2ltYWdlL2FiNjc2MTZkMDAwMGIyNzM4NzZkZDJiYmUxN2UxNTIwOGIyNTc3OWIAAAAAAAAAAA=="}
2023-08-08 21:08:42.864  INFO 19412 --- [  XNIO-1 task-2] lavalink.server.io.RequestLoggingFilter  : PATCH /v3/sessions/8euhnj3yq3py50gy/players/639211220280541194/?noReplace=false, client=127.0.0.1, payload={"encodedTrack":null}
2023-08-08 21:08:43.881  INFO 19412 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://open.spotify.com/track/52LL3IFB8N3PaJmoZ8Xii1"
2023-08-08 21:08:43.952  INFO 19412 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track The Way You Used To Do
2023-08-08 21:08:43.955  INFO 19412 --- [  XNIO-1 task-2] lavalink.server.io.RequestLoggingFilter  : GET /v3/loadtracks?identifier=https%3A%2F%2Fopen.spotify.com%2Ftrack%2F52LL3IFB8N3PaJmoZ8Xii1, client=127.0.0.1
2023-08-08 21:09:15.119  INFO 19412 --- [  XNIO-1 task-2] lavalink.server.io.RequestLoggingFilter  : PATCH /v3/sessions/8euhnj3yq3py50gy/players/639211220280541194/?noReplace=false, client=127.0.0.1, payload={"encodedTrack":null}
```

**Comment by topi314** [comment]
ideally you'd test with the same track...

**Comment by LucasB25** [comment]
It's going to be complicated, it was autoplay

**Comment by topi314** [comment]
it literally prints what it plays in the logs...
https://open.spotify.com/track/1sUTfgduT0WIQO8kXKXxLC

**Comment by LucasB25** [comment]
> it literally prints what it plays in the logs... https://open.spotify.com/track/1sUTfgduT0WIQO8kXKXxLC

https://sourceb.in/fWDSpOHSfq no resolved

**Comment by topi314** [comment]
you are not using the snapshot build

**Comment by LucasB25** [comment]
```
    - dependency: "com.github.TopiSenpai.LavaSrc:lavasrc-plugin:3.2.5"
      repository: "https://maven.topi.wtf/snapshots"
```

**Comment by topi314** [comment]
> use the first 7 char commit hash from the commit above as the version

**Comment by topi314** [comment]
Perhaps you should provide an apple music token or disable apple music

Read the error

**Comment by LucasB25** [comment]
```
2023-08-09 20:44:27.019  INFO 12810 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track Stay with Me
2023-08-09 20:44:27.021  INFO 12810 --- [  XNIO-1 task-2] lavalink.server.io.RequestLoggingFilter  : GET /v3/loadtracks?identifier=https%3A%2F%2Fopen.spotify.com%2Ftrack%2F7fLTytvnvxy653VWxflTRf, client=127.0.0.1
2023-08-09 20:48:50.821  INFO 12810 --- [  XNIO-1 task-2] lavalink.server.io.RequestLoggingFilter  : PATCH /v3/sessions/i89fh1i3f1vpjc3h/players/639211220280541194/?noReplace=false, client=127.0.0.1, payload={"encodedTrack":"QAAA0gIADFN0YXkgd2l0aCBNZQAFRmFjZXMAAAAAAARDQAAWN2ZMVHl0dm52eHk2NTNWV3hmbFRSZgABADVodHRwczovL29wZW4uc3BvdGlmeS5jb20vdHJhY2svN2ZMVHl0dm52eHk2NTNWV3hmbFRSZgAHc3BvdGlmeQEADFVTV0IxMDEwMzg1NQEAQGh0dHBzOi8vaS5zY2RuLmNvL2ltYWdlL2FiNjc2MTZkMDAwMGIyNzMyODdjZjQ2NTkwYTc4MWI4YTAzZTE3NGUAAAAAAAAAAA=="}
2023-08-09 20:48:51.841  INFO 12810 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://open.spotify.com/track/2P7d62DM2Q1A9i6kkc4rgl"
2023-08-09 20:48:53.370  INFO 12810 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track I Was Just Leaving
2023-08-09 20:48:53.380  INFO 12810 --- [  XNIO-1 task-2] lavalink.server.io.RequestLoggingFilter  : GET /v3/loadtracks?identifier=https%3A%2F%2Fopen.spotify.com%2Ftrack%2F2P7d62DM2Q1A9i6kkc4rgl, client=127.0.0.1
2023-08-09 20:54:15.520  INFO 12810 --- [  XNIO-1 task-2] lavalink.server.io.RequestLoggingFilter  : PATCH /v3/sessions/i89fh1i3f1vpjc3h/players/639211220280541194/?noReplace=false, client=127.0.0.1, payload={"encodedTrack":"QAAA4QIAEkkgV2FzIEp1c3QgTGVhdmluZwAOUnlhbiBNb250YmxlYXUAAAAAAAK5tgAWMlA3ZDYyRE0yUTFBOWk2a2tjNHJnbAABADVodHRwczovL29wZW4uc3BvdGlmeS5jb20vdHJhY2svMlA3ZDYyRE0yUTFBOWk2a2tjNHJnbAAHc3BvdGlmeQEADFRDQUNXMTc4ODU4NQEAQGh0dHBzOi8vaS5zY2RuLmNvL2ltYWdlL2FiNjc2MTZkMDAwMGIyNzMwYmMyYjQyNWUzMTc2MDExOWQxMDgzNGEAAAAAAAAAAA=="}
2023-08-09 20:54:15.842  INFO 12810 --- [  XNIO-1 task-2] lavalink.server.io.RequestLoggingFilter  : PATCH /v3/sessions/i89fh1i3f1vpjc3h/players/639211220280541194/?noReplace=false, client=127.0.0.1, payload={"encodedTrack":null}
2023-08-09 20:54:16.015  INFO 12810 --- [  XNIO-1 task-2] lavalink.server.io.RequestLoggingFilter  : PATCH /v3/sessions/i89fh1i3f1vpjc3h/players/639211220280541194/?noReplace=false, client=127.0.0.1, payload={"encodedTrack":null}
2023-08-09 20:54:16.590  INFO 12810 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://open.spotify.com/track/2l9UM2IVGSulrohfekmKdr"
2023-08-09 20:54:16.653  INFO 12810 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track A Song For You
2023-08-09 20:54:16.656  INFO 12810 --- [  XNIO-1 task-2] lavalink.server.io.RequestLoggingFilter  : GET /v3/loadtracks?identifier=https%3A%2F%2Fopen.spotify.com%2Ftrack%2F2l9UM2IVGSulrohfekmKdr, client=127.0.0.1
```

{"encodedTrack":null} - I have null returns

**Comment by topi314** [comment]
fixed in https://github.com/topi314/LavaSrc/releases/tag/3.2.6
